import type { Product, User, Transaction, Message, Channel, Course, StoreProduct, ChatHistory, Notification } from '@/types';

export const currentUser: User = {
  id: '1',
  name: 'James Carter',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
  role: 'Pro Seller',
  isPro: true,
  country: 'United States',
  flag: '🇺🇸',
  online: true,
};

export const communityMembers: User[] = [
  { id: '1', name: 'James Carter', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James', role: 'Pro Seller', isPro: true, country: 'United States', flag: '🇺🇸', online: true },
  { id: '2', name: 'Sophia Martinez', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophia', role: 'Creator', isPro: true, country: 'United States', flag: '🇺🇸', online: true },
  { id: '3', name: 'Arjun Patel', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arjun', role: 'Seller', isPro: false, country: 'India', flag: '🇮🇳', online: true },
  { id: '4', name: 'Lena Müller', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lena', role: 'Designer', isPro: true, country: 'Germany', flag: '🇩🇪', online: true },
  { id: '5', name: 'Carlos Silva', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos', role: 'Marketer', isPro: false, country: 'Brazil', flag: '🇧🇷', online: true },
  { id: '6', name: 'Priya Sharma', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya', role: 'Educator', isPro: true, country: 'India', flag: '🇮🇳', online: false },
];

export const products: Product[] = [
  {
    id: '1',
    image: 'https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?w=400&h=300&fit=crop',
    category: 'AI Tool',
    categoryColor: 'bg-green-100 text-green-700',
    title: 'AI Writer Pro – Content Generation Suite',
    seller: 'WriteGen Studio',
    sellerVerified: true,
    rating: 4.9,
    reviewCount: '2.1K',
    price: 29,
    originalPrice: 59,
    badge: 'Best Seller',
    type: 'digital',
    tags: ['AI', 'Writing', 'Marketing'],
  },
  {
    id: '2',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
    category: 'Course',
    categoryColor: 'bg-blue-100 text-blue-700',
    title: 'Ecommerce Mastery – Sell Globally in 30 Days',
    seller: 'Alex Morgan',
    sellerVerified: true,
    rating: 4.8,
    reviewCount: '1.2K',
    price: 49,
    originalPrice: 99,
    badge: 'Trending',
    type: 'digital',
    tags: ['Ecommerce', 'Business', 'Marketing'],
  },
  {
    id: '3',
    image: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=400&h=300&fit=crop',
    category: 'Template',
    categoryColor: 'bg-purple-100 text-purple-700',
    title: 'Notion Business OS – Productivity Bundle',
    seller: 'MindLift Co.',
    sellerVerified: true,
    rating: 4.7,
    reviewCount: '876',
    price: 19,
    originalPrice: 39,
    badge: 'Top Rated',
    type: 'digital',
    tags: ['Notion', 'Productivity', 'Templates'],
  },
  {
    id: '4',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop',
    category: 'Ebook',
    categoryColor: 'bg-orange-100 text-orange-700',
    title: 'Social Media Growth Playbook 2024',
    seller: 'Digital Vault',
    sellerVerified: false,
    rating: 4.5,
    reviewCount: '432',
    price: 14,
    originalPrice: 29,
    type: 'digital',
    tags: ['Social Media', 'Growth', 'Marketing'],
  },
  {
    id: '5',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=300&fit=crop',
    category: 'Physical',
    categoryColor: 'bg-gray-100 text-gray-700',
    title: 'Premium Noise-Cancelling Headphones',
    seller: 'AudioPro Store',
    sellerVerified: true,
    rating: 4.6,
    reviewCount: '567',
    price: 89,
    originalPrice: 149,
    badge: 'Best Seller',
    type: 'physical',
    tags: ['Electronics', 'Audio', 'Headphones'],
  },
  {
    id: '6',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop',
    category: 'Physical',
    categoryColor: 'bg-pink-100 text-pink-700',
    title: 'Urban Stride Runners – Limited Edition',
    seller: 'StepUp Brand',
    sellerVerified: true,
    rating: 4.4,
    reviewCount: '289',
    price: 79,
    originalPrice: 129,
    type: 'physical',
    tags: ['Sneakers', 'Fashion', 'Sports'],
  },
  {
    id: '7',
    image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&h=300&fit=crop',
    category: 'AI Tool',
    categoryColor: 'bg-green-100 text-green-700',
    title: 'AI Store Kit – Complete Automation Bundle',
    seller: 'AutoSell Labs',
    sellerVerified: true,
    rating: 4.8,
    reviewCount: '1.4K',
    price: 39,
    originalPrice: 79,
    badge: 'Trending',
    type: 'digital',
    tags: ['AI', 'Automation', 'Store'],
  },
  {
    id: '8',
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=300&fit=crop',
    category: 'Course',
    categoryColor: 'bg-blue-100 text-blue-700',
    title: 'Digital Marketing Bootcamp – Beginner to Pro',
    seller: 'GrowthHackr',
    sellerVerified: false,
    rating: 4.6,
    reviewCount: '954',
    price: 59,
    originalPrice: 119,
    type: 'digital',
    tags: ['Marketing', 'Digital', 'Ads'],
  },
  {
    id: '9',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&h=300&fit=crop',
    category: 'Template',
    categoryColor: 'bg-purple-100 text-purple-700',
    title: 'Canva Brand Identity Kit – 200+ Templates',
    seller: 'DesignForge',
    sellerVerified: true,
    rating: 4.9,
    reviewCount: '3.2K',
    price: 24,
    originalPrice: 49,
    badge: 'Best Seller',
    type: 'digital',
    tags: ['Design', 'Canva', 'Branding'],
  },
  {
    id: '10',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop',
    category: 'Course',
    categoryColor: 'bg-blue-100 text-blue-700',
    title: 'Freelancing Freedom – Build a 6-Figure Business',
    seller: 'NomadPro Academy',
    sellerVerified: true,
    rating: 4.7,
    reviewCount: '712',
    price: 79,
    originalPrice: 149,
    type: 'digital',
    tags: ['Freelancing', 'Business', 'Income'],
  },
  {
    id: '11',
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=300&fit=crop',
    category: 'Ebook',
    categoryColor: 'bg-orange-100 text-orange-700',
    title: 'Crypto Trading Fundamentals – Complete Guide',
    seller: 'CryptoEdge',
    sellerVerified: false,
    rating: 4.3,
    reviewCount: '187',
    price: 12,
    originalPrice: 24,
    type: 'digital',
    tags: ['Crypto', 'Finance', 'Trading'],
  },
  {
    id: '12',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop',
    category: 'AI Tool',
    categoryColor: 'bg-green-100 text-green-700',
    title: 'SEO Power Pack – Rank Faster with AI',
    seller: 'RankBoost AI',
    sellerVerified: true,
    rating: 4.8,
    reviewCount: '1.8K',
    price: 34,
    originalPrice: 69,
    badge: 'Top Rated',
    type: 'digital',
    tags: ['SEO', 'AI', 'Marketing'],
  },
];

export const storeProducts: StoreProduct[] = [
  { id: 's1', image: 'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=300&h=200&fit=crop', category: 'Home Decor', categoryColor: 'bg-amber-100 text-amber-700', title: 'Minimalist Ceramic Vase', price: 29.99, rating: 4.8, reviewCount: '342', status: 'Active' },
  { id: 's2', image: 'https://images.unsplash.com/photo-1513506003901-1e6a35cc3490?w=300&h=200&fit=crop', category: 'Lighting', categoryColor: 'bg-yellow-100 text-yellow-700', title: 'Nordic Pendant Light Fixture', price: 74.99, rating: 4.6, reviewCount: '128', status: 'Active' },
  { id: 's3', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=300&h=200&fit=crop', category: 'Kitchen', categoryColor: 'bg-green-100 text-green-700', title: 'Artisan Wooden Cutting Board', price: 44.99, rating: 4.9, reviewCount: '567', status: 'Active' },
  { id: 's4', image: 'https://images.unsplash.com/photo-1558997519-83ea9252eeb8?w=300&h=200&fit=crop', category: 'Storage', categoryColor: 'bg-stone-100 text-stone-700', title: 'Bamboo Organizer Set – 3pc', price: 34.99, rating: 4.5, reviewCount: '243', status: 'Active' },
  { id: 's5', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=300&h=200&fit=crop', category: 'Furniture', categoryColor: 'bg-orange-100 text-orange-700', title: 'Linen Throw Pillow Set – 4pc', price: 52.99, rating: 4.7, reviewCount: '189', status: 'Active' },
  { id: 's6', image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=300&h=200&fit=crop', category: 'Wall Decor', categoryColor: 'bg-purple-100 text-purple-700', title: 'Boho Macrame Wall Hanging', price: 39.99, rating: 4.4, reviewCount: '97', status: 'Draft' },
  { id: 's7', image: 'https://images.unsplash.com/photo-1564540574859-0dfb63985953?w=300&h=200&fit=crop', category: 'Bathroom', categoryColor: 'bg-teal-100 text-teal-700', title: 'Marble Effect Soap Dispenser', price: 22.99, rating: 4.6, reviewCount: '214', status: 'Active' },
  { id: 's8', image: 'https://images.unsplash.com/photo-1563298723-dcfebaa392e3?w=300&h=200&fit=crop', category: 'Bedding', categoryColor: 'bg-blue-100 text-blue-700', title: 'Luxury Cotton Duvet Cover', price: 89.99, rating: 4.8, reviewCount: '421', status: 'Active' },
];

export const transactions: Transaction[] = [
  { id: 't1', date: 'May 24, 2024', time: '10:32 AM', description: 'Withdrawal to Bank Account', accountMask: '**** **** **** 4587', type: 'Withdrawal', paymentMethod: 'Bank', amount: -520, status: 'Completed', balance: 2458.30 },
  { id: 't2', date: 'May 23, 2024', time: '2:15 PM', description: 'Withdrawal to PayPal', accountMask: 'james@example.com', type: 'Withdrawal', paymentMethod: 'PayPal', amount: -300, status: 'Completed', balance: 2978.30 },
  { id: 't3', date: 'May 22, 2024', time: '9:45 AM', description: 'Withdrawal to Wise', accountMask: '**** 7823', type: 'Withdrawal', paymentMethod: 'Wise', amount: -649, status: 'Completed', balance: 3278.30 },
  { id: 't4', date: 'May 20, 2024', time: '4:20 PM', description: 'Withdrawal to Bank Account', accountMask: '**** **** **** 4587', type: 'Withdrawal', paymentMethod: 'Bank', amount: -300, status: 'Completed', balance: 3927.30 },
  { id: 't5', date: 'May 19, 2024', time: '11:10 AM', description: 'Withdrawal to PayPal', accountMask: 'james@example.com', type: 'Withdrawal', paymentMethod: 'PayPal', amount: -650, status: 'Completed', balance: 4227.30 },
];

export const chatMessages: Message[] = [
  {
    id: 'm1',
    user: communityMembers[1],
    content: 'Just launched my new digital product — a full business template pack! 🎉 Already got 12 sales in the first hour. Geotradez is incredible for creators!',
    time: '10:32 AM',
    reactions: [{ emoji: '👍', count: 14 }, { emoji: '🔥', count: 8 }, { emoji: '🎉', count: 6 }],
  },
  {
    id: 'm2',
    user: communityMembers[2],
    content: 'Congrats Sophia! That\'s amazing! 🙌 I\'m still setting up my store but seeing results like yours keeps me motivated. Any tips for the first launch?',
    time: '10:34 AM',
    reactions: [{ emoji: '👍', count: 6 }],
  },
  {
    id: 'm3',
    user: communityMembers[3],
    content: 'AI tools are a game changer for content creation. I use the AI Writer Pro tool and cut my content production time by 70%. Highly recommend for anyone struggling with descriptions!',
    time: '10:36 AM',
    reactions: [{ emoji: '💯', count: 11 }, { emoji: '👍', count: 9 }],
  },
  {
    id: 'm4',
    user: communityMembers[4],
    content: 'Looking for collaborators for a joint digital product launch 🌍 — I\'m a marketer, need a designer and developer. Drop me a DM if interested!',
    time: '10:38 AM',
    reactions: [{ emoji: '🤝', count: 4 }],
    embed: {
      icon: 'N',
      title: 'Minimal Business OS – Notion Template',
      subtitle: 'by MindLift • geotradez.com',
    },
  },
];

export const channels: Channel[] = [
  { id: 'c1', name: 'announcements', type: 'announcement', section: 'ANNOUNCEMENTS' },
  { id: 'c2', name: 'Global Chat', type: 'text', section: 'ANNOUNCEMENTS', active: true },
  { id: 'c3', name: 'E-Commerce Growth', type: 'text', section: 'CUSTOM CHANNELS' },
  { id: 'c4', name: 'Digital Products', type: 'text', section: 'CUSTOM CHANNELS' },
  { id: 'c5', name: 'Store Marketing', type: 'text', section: 'CUSTOM CHANNELS' },
  { id: 'c6', name: 'Voice Rooms', type: 'voice', section: 'CUSTOM CHANNELS' },
];

export const courses: Course[] = [
  {
    id: 'co1',
    thumbnail: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=400&h=250&fit=crop',
    category: 'Business',
    title: 'Ecommerce Blueprint: Build a 6-Figure Store',
    instructor: 'Alex Morgan',
    instructorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    duration: '8h 32m',
    difficulty: 'Intermediate',
    rating: 4.9,
    students: '12.4K',
    price: 79,
    enrolled: true,
    progress: 65,
  },
  {
    id: 'co2',
    thumbnail: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&h=250&fit=crop',
    category: 'AI Tools',
    title: 'AI-Powered Marketing: ChatGPT for Sellers',
    instructor: 'Priya Sharma',
    instructorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    duration: '5h 15m',
    difficulty: 'Beginner',
    rating: 4.8,
    students: '8.7K',
    price: 49,
    enrolled: true,
    progress: 30,
  },
  {
    id: 'co3',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=250&fit=crop',
    category: 'Marketing',
    title: 'Facebook & Instagram Ads Mastery 2024',
    instructor: 'Carlos Silva',
    instructorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
    duration: '11h 45m',
    difficulty: 'Intermediate',
    rating: 4.7,
    students: '15.2K',
    price: 89,
  },
  {
    id: 'co4',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&h=250&fit=crop',
    category: 'Design',
    title: 'Canva Mastery: Design That Sells',
    instructor: 'Lena Müller',
    instructorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lena',
    duration: '6h 20m',
    difficulty: 'Beginner',
    rating: 4.9,
    students: '9.8K',
    price: 'Free',
  },
  {
    id: 'co5',
    thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=250&fit=crop',
    category: 'Business',
    title: 'Freelancing to Freedom: Scale Your Income',
    instructor: 'James Carter',
    instructorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    duration: '9h 10m',
    difficulty: 'Advanced',
    rating: 4.8,
    students: '5.1K',
    price: 99,
  },
  {
    id: 'co6',
    thumbnail: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=250&fit=crop',
    category: 'Finance',
    title: 'Creator Economy: Monetize Your Expertise',
    instructor: 'Arjun Patel',
    instructorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arjun',
    duration: '4h 50m',
    difficulty: 'Beginner',
    rating: 4.6,
    students: '6.3K',
    price: 39,
  },
  {
    id: 'co7',
    thumbnail: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400&h=250&fit=crop',
    category: 'AI Tools',
    title: 'Build AI Products: No Code, Full Power',
    instructor: 'Sophia Martinez',
    instructorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophia',
    duration: '7h 30m',
    difficulty: 'Intermediate',
    rating: 4.9,
    students: '11.2K',
    price: 69,
  },
  {
    id: 'co8',
    thumbnail: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400&h=250&fit=crop',
    category: 'Marketing',
    title: 'SEO Fundamentals for Digital Sellers',
    instructor: 'Alex Morgan',
    instructorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    duration: '3h 40m',
    difficulty: 'Beginner',
    rating: 4.5,
    students: '7.6K',
    price: 'Free',
  },
];

export const chatHistory: ChatHistory[] = [
  { id: 'ch1', title: 'Product description for AI Bundle', category: 'Product', time: '10:24 AM' },
  { id: 'ch2', title: 'Instagram ad copy – Flash Sale', category: 'Ad', time: 'Yesterday' },
  { id: 'ch3', title: 'Store return policy template', category: 'Store', time: 'May 12' },
  { id: 'ch4', title: 'Product ideas for Q3 launch', category: 'Product', time: 'May 11' },
  { id: 'ch5', title: 'Email campaign for new subscribers', category: 'Email', time: 'May 10' },
  { id: 'ch6', title: 'Landing page content for course', category: 'Store', time: 'May 9' },
];

export const notifications: Notification[] = [
  { id: 'n1', type: 'order', title: 'New Order Received', description: 'AI Writer Pro was purchased by Sarah K.', time: '5 min ago', read: false },
  { id: 'n2', type: 'review', title: 'New 5-Star Review', description: '"Absolutely incredible tool!" — Michael T.', time: '1 hr ago', read: false },
  { id: 'n3', type: 'message', title: 'New Message', description: 'Arjun Patel sent you a DM', time: '2 hrs ago', read: true },
  { id: 'n4', type: 'system', title: 'Payout Processed', description: '$520.00 sent to your bank account', time: 'Yesterday', read: true },
  { id: 'n5', type: 'order', title: 'Order Completed', description: 'Notion Business OS – order #4821', time: '2 days ago', read: true },
];

export const revenueData = [
  { date: 'Apr 18', revenue: 1200 },
  { date: 'Apr 21', revenue: 1800 },
  { date: 'Apr 24', revenue: 1400 },
  { date: 'Apr 27', revenue: 2100 },
  { date: 'Apr 30', revenue: 1900 },
  { date: 'May 3', revenue: 2400 },
  { date: 'May 6', revenue: 2200 },
  { date: 'May 9', revenue: 2800 },
  { date: 'May 12', revenue: 3100 },
  { date: 'May 15', revenue: 2900 },
  { date: 'May 18', revenue: 3600 },
  { date: 'May 21', revenue: 4200 },
  { date: 'May 24', revenue: 3800 },
];

export const savedItems = [
  { id: 'sv1', image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=80&h=80&fit=crop', name: 'Boho Floor Rug', category: 'Home Decor', price: 89.99 },
  { id: 'sv2', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=80&h=80&fit=crop', name: 'Smart WiFi Plug', category: 'Electronics', price: 24.99 },
  { id: 'sv3', image: 'https://images.unsplash.com/photo-1559583985-c80d8ad9b29f?w=80&h=80&fit=crop', name: 'Aromatherapy Diffuser', category: 'Beauty', price: 35.00 },
];
